### ISSUE TITLE
Fan speed control stopped working

### ISSUE THREAD

**Issue by brianjstarr** [dalinicus/homeassistant-acinfinity#66]
**Describe the bug**
When I try to set the fan on speed through Home Assistant, it doesn't work and I get various error messages in the log.

**To Reproduce**
Try to set the fan on speed by whatever means.
It fails.
There are various errors in the log

**Expected behavior**
Fan on speed changes without error

**Screenshots**
Various log messages:
Failed to perform the action number/set_value. {'msg': 'Something went wrong with your request.\nPlease try again later.', 'code': 100001}
This error originated from a custom integration.
Logger: custom_components.ac_infinity.core
Source: custom_components/ac_infinity/core.py:644
integration: AC Infinity ([documentation](https://github.com/dalinicus/homeassistant-acinfinity), [issues](https://github.com/dalinicus/homeassistant-acinfinity))
First occurred: 12:49:05 PM (3 occurrences)
Last logged: 12:50:20 PM

Unable to update settings. Retry attempt limit exceeded
Traceback (most recent call last):
  File "/config/custom_components/ac_infinity/core.py", line 644, in update_port_controls
    await self._client.set_device_mode_settings(
  File "/config/custom_components/ac_infinity/client.py", line 129, in set_device_mode_settings
    _ = await self.__post(API_URL_ADD_DEV_MODE, settings, headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ac_infinity/client.py", line 236, in __post
    raise ACInfinityClientRequestFailed(json)
custom_components.ac_infinity.client.ACInfinityClientRequestFailed: {'msg': 'Something went wrong with your request.\nPlease try again later.', 'code': 100001}

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 12:49:05 PM (2 occurrences)
Last logged: 12:49:18 PM

[547705161616] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 120, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/ac_infinity/number.py", line 686, in async_set_native_value
    await self.entity_description.set_value_fn(self, self.port, value)
  File "/config/custom_components/ac_infinity/core.py", line 624, in update_port_control
    await self.update_port_controls(
  File "/config/custom_components/ac_infinity/core.py", line 644, in update_port_controls
    await self._client.set_device_mode_settings(
  File "/config/custom_components/ac_infinity/client.py", line 129, in set_device_mode_settings
    _ = await self.__post(API_URL_ADD_DEV_MODE, settings, headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ac_infinity/client.py", line 236, in __post
    raise ACInfinityClientRequestFailed(json)
custom_components.ac_infinity.client.ACInfinityClientRequestFailed: {'msg': 'Something went wrong with your request.\nPlease try again later.', 'code': 100001}

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 12:48:02 PM (4 occurrences)
Last logged: 12:48:07 PM

Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/frontend", "/config/custom_components/hacs/hacs_frontend_experimental", False)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 49: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/iconset.js", "/config/custom_components/hacs/iconset.js", True)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 57: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brianjstarr** [comment]
I “fixed” it by unplugging the fan, then plugging it back in.Sent from my iPadOn Aug 12, 2024, at 9:52 PM, Ryan Mattson ***@***.***> wrote:﻿
Hey, thanks for making the issue thread.
Yeah to be honest, this really just looks like API instability to me.  It happens from time to time and there's really nothing we can do about it other than just wait for it to recover.
Before we get to far into debugging can you please verify the following:

You're on the current version 1.6.0 (release 4 days ago)
You're consistently still experiencing this now that a few hours have passed.

**Comment by dalinicus** [comment]
yeah that checks out.

gonna chalk it up to API or WIFI problems.  If you continue to have issues, let me know.
